//CONTAINS PREPROCESSORS THAT NEEDS TO BE IN BOARDFILE
#include <stdint.h>
#include "stm32f4xx_ll_dma.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_usart.h"

#ifndef  BOARDFILE_H
#define  BOARDFILE_H

////USART1
//#define UART1_TX_GPIO_PIN LL_GPIO_PIN_9
//#define UART1_RX_GPIO_PIN LL_GPIO_PIN_10
//#define UART1_TX_GPIO_PORT GPIOA
//#define UART1_RX_GPIO_PORT GPIOA
//#define UART1_GPIO_AF 0b111
//#define UART1_RX_DMA_STREAM 5
//#define UART1_RX_DMA_NUMBER DMA2
//#define UART1_TX_DMA_STREAM 7
//#define UART1_TX_DMA_NUMBER DMA2
//#define UART1_TX_DMA_CHANNEL LL_DMA_CHANNEL_4
//#define UART1_RX_DMA_CHANNEL LL_DMA_CHANNEL_4

//USART2
#define UART2_TX_GPIO_PIN LL_GPIO_PIN_2
#define UART2_RX_GPIO_PIN LL_GPIO_PIN_3
#define UART2_TX_GPIO_PORT GPIOA
#define UART2_RX_GPIO_PORT GPIOA
#define UART2_GPIO_AF 0b111
#define UART2_RX_DMA_STREAM 5
#define UART2_RX_DMA_NUMBER DMA1
#define UART2_TX_DMA_STREAM 6
#define UART2_TX_DMA_NUMBER DMA1
#define UART2_TX_DMA_CHANNEL LL_DMA_CHANNEL_4
#define UART2_RX_DMA_CHANNEL LL_DMA_CHANNEL_4

////USART6
//#define UART6_TX_GPIO_PIN LL_GPIO_PIN_11
//#define UART6_RX_GPIO_PIN LL_GPIO_PIN_12
//#define UART6_TX_GPIO_PORT GPIOA
//#define UART6_RX_GPIO_PORT GPIOA
//#define UART6_GPIO_AF 0b1000
//#define UART6_RX_DMA_STREAM 2
//#define UART6_RX_DMA_NUMBER DMA2
//#define UART6_TX_DMA_STREAM 6
//#define UART6_TX_DMA_NUMBER DMA2
//#define UART6_TX_DMA_CHANNEL LL_DMA_CHANNEL_5
//#define UART6_RX_DMA_CHANNEL LL_DMA_CHANNEL_5

#define NUM_UARTS 3

extern uint32_t UARTS[NUM_UARTS];
extern uint32_t UART_TX_GPIO_PINS[NUM_UARTS];
extern uint32_t UART_RX_GPIO_PINS[NUM_UARTS];
extern GPIO_TypeDef *UART_TX_GPIO_PORTS[NUM_UARTS];
extern GPIO_TypeDef *UART_RX_GPIO_PORTS[NUM_UARTS];
extern uint32_t UART_GPIO_AF[NUM_UARTS];
extern uint32_t UART_RX_DMA_STREAM[NUM_UARTS];
extern uint32_t UART_TX_DMA_STREAM[NUM_UARTS];
extern DMA_TypeDef *UART_RX_DMA_NUMBER[NUM_UARTS];
extern DMA_TypeDef *UART_TX_DMA_NUMBER[NUM_UARTS];
extern uint32_t UART_RX_DMA_CHANNEL[NUM_UARTS];
extern uint32_t UART_TX_DMA_CHANNEL[NUM_UARTS];


#endif
